/* Generated by src/eleventy/service-worker.js — do not edit. */
const BUILD_ID = "c92d379a6a4498eb";
const PRECACHE_URLS = ["/css/base.63e4426846.css","/css/blog/posts/2026-05-22-story-of-our-website-part-one/post.89095c2f3d.css","/css/default.c9127f66ec.css","/fonts/atkinson-hyperlegible-next-latin-wght-italic.4a5037bfaf.woff2","/fonts/atkinson-hyperlegible-next-latin-wght-normal.18b2a1a39a.woff2","/js/blog.8226b46330.js","/js/core.19a18ad73e.js","/js/error.fa2ad40686.js","/js/parallax.8a1f5c8d1f.js","/js/qa.0f30aa8ab7.js","/themes/manifest.3e3b7566fb.json","/themes/night/night.188e2bec7a.css","/themes/night/theme.json","/themes/north-light/north-light.5b58ba0923.css","/themes/north-light/theme.json","/themes/parallax/parallax.5b5165e75d.json","/themes/parallax/parallax.c1000f9af6.css","/themes/parallax/theme.json","/themes/pure-light/pure-light.29335f8310.css","/themes/pure-light/theme.json","/themes/skybox-3D/skybox-3D.c1000f9af6.css","/themes/skybox-3D/skybox.8645afa1b2.json","/themes/skybox-3D/theme.json"];

const CACHE_NAME = 'precache-' + BUILD_ID;

// Lifecycle, deliberately: this worker never calls skipWaiting, and it claims
// clients only on its very FIRST install. A page keeps the cache it loaded under
// for its whole lifetime, so its late/lazy fetches always resolve from its own
// cache even after the server wiped that build; a new worker waits and only
// activates once every old-version client is gone (a single-tab navigation
// releases the last one), at which point deleting the old cache cannot pull the
// rug from a live page. Claiming on first install lets the very first visit's
// page route its own late fetches (a theme bundle loaded on switch) through the
// cache too — safe because there is no older version to mismatch. Claiming on an
// UPDATE, or calling skipWaiting, would instead activate the new worker under a
// still-rendered old page and delete the cache it is lazily fetching from —
// reintroducing the exact 404 this worker exists to prevent.

self.addEventListener('install', (event) => {
    event.waitUntil((async () => {
        const cache = await caches.open(CACHE_NAME);
        // The critical shell only. {cache: 'reload'} bypasses the 10-minute HTTP
        // cache so we capture THIS deploy's bytes; addAll is atomic, so a partial
        // set never activates.
        await cache.addAll(PRECACHE_URLS.map((url) => new Request(url, { cache: 'reload' })));
    })());
});

self.addEventListener('activate', (event) => {
    event.waitUntil((async () => {
        const names = await caches.keys();
        const firstInstall = !names.some((name) => name !== CACHE_NAME && name.startsWith('precache-'));
        await Promise.all(names.filter((name) => name !== CACHE_NAME).map((name) => caches.delete(name)));
        if (firstInstall) await self.clients.claim();
    })());
});

self.addEventListener('fetch', (event) => {
    const request = event.request;
    if (request.method !== 'GET') return;
    const url = new URL(request.url);
    if (url.origin !== self.location.origin) return;

    // Navigations: network-first so HTML stays fresh online; cache each success so
    // a visited page still loads offline, and fall back to that copy when offline.
    if (request.mode === 'navigate') {
        event.respondWith((async () => {
            const cache = await caches.open(CACHE_NAME);
            try {
                const response = await fetch(request);
                if (response.status === 200) event.waitUntil(cache.put(request, response.clone()));
                return response;
            } catch (error) {
                return (await cache.match(request)) || (await cache.match(url.pathname)) || Response.error();
            }
        })());
        return;
    }

    // Subresources. Content-hashed URLs are immutable, so they are cache-first
    // forever. Stable-named assets (content pictures) are stale-while-revalidate:
    // serve the cached copy immediately, then refresh it in the background so a
    // changed picture at the same URL appears on the next view without waiting for
    // a worker update. A miss — a not-yet-cached image/texture, or a hashed asset
    // from a newer build than this worker — is fetched and kept, so a later clean
    // deploy cannot 404 it for this still-open page.
    const immutable = /\.[0-9a-f]{10}\.[^.\/]+$/.test(url.pathname);
    event.respondWith((async () => {
        const cache = await caches.open(CACHE_NAME);
        const cached = await cache.match(request);
        if (cached) {
            if (!immutable) {
                event.waitUntil((async () => {
                    try {
                        const fresh = await fetch(request);
                        if (fresh.status === 200) await cache.put(request, fresh);
                    } catch (error) { /* keep the cached copy */ }
                })());
            }
            return cached;
        }
        // Immutable miss: the exact bytes may live in a sibling cache — a newer
        // build's worker that has installed and precached but not yet activated.
        // A content-hashed URL is unique to its bytes, so any cache's copy is the
        // right one, and it survives a later clean deploy the network no longer has.
        if (immutable) {
            const sibling = await caches.match(request);
            if (sibling) return sibling;
        }
        const response = await fetch(request);
        if (response.status === 200) {
            event.waitUntil(cache.put(request, response.clone()));
        }
        return response;
    })());
});
